### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-y#1]
I'd like to be able to add more (or less) brightness to images.

**Describe the solution you'd like**
The list `y_presets` should contain `brightness` with a value, something like this:

```yaml
---
y_presets:
  - brightness:
    amount: -14
```

**Additional context**
[ImageMagick on brightness (& contrast)](https://www.imagemagick.org/script/command-line-options.php#brightness-contrast)
