### ISSUE TITLE
Contrast control

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-y#2]
I'd like to be able to add more (or less) contrast to images.

**Describe the solution you'd like**
The list `y_presets` should contain `contrast` with a value, something like this:

```yaml
---
y_presets:
  - contrast:
    amount: 23
```

**Additional context**
[ImageMagick on contrast (& brightness)](https://www.imagemagick.org/script/command-line-options.php#brightness-contrast)
