### ISSUE TITLE
Watermarking

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-y#4]
I'd like to be able to add a logo as a watermark over images.

**Describe the solution you'd like**
The list `y_presets` should contain `watermark` with a value, something like this:

```yaml
---
y_presets:
  - watermark:
    image: ansible.jpg
```

**Additional context**
[ImageMagick on watermarking](https://www.imagemagick.org/Usage/compose/#watermark)

The logo should always go in the bottom right of an image. (SouthEast)
